import argparse
import json
from datetime import datetime
from pathlib import Path

INBOX_DIR = Path("trigger") / "inbox"


def build_payload(short_description: str, description: str, urgency: str, impact: str):
    return {
        "short_description": short_description,
        "description": description,
        "urgency": urgency,
        "impact": impact,
        "comments": "Generated by create_inbox_record.py"
    }


def main():
    parser = argparse.ArgumentParser(description="Create a JSON input record in trigger/inbox")
    parser.add_argument("--action", default="create", choices=["create", "close"],
                        help="create: open new incident | close: close existing incident")
    parser.add_argument("--short", default="Pilot alert from record generator", help="short_description (create only)")
    parser.add_argument("--desc", default="Generated test record dropped into inbox.", help="description (create only)")
    parser.add_argument("--urgency", default="2", choices=["1", "2", "3"], help="Urgency 1-3 (create only)")
    parser.add_argument("--impact", default="2", choices=["1", "2", "3"], help="Impact 1-3 (create only)")
    parser.add_argument("--incident", default="", help="Incident number to close e.g. INC0010011 (close only)")
    parser.add_argument("--notes", default="System resolved. Ticket closed automatically.",
                        help="Close notes (close only)")
    args = parser.parse_args()

    INBOX_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    if args.action == "close":
        if not args.incident:
            print("Error: --incident is required when using --action close")
            return
        payload = {
            "action": "close",
            "incident_number": args.incident,
            "close_notes": args.notes,
        }
        file_path = INBOX_DIR / f"close_{timestamp}.json"
    else:
        payload = build_payload(args.short, args.desc, args.urgency, args.impact)
        file_path = INBOX_DIR / f"record_{timestamp}.json"

    file_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Created: {file_path}")


if __name__ == "__main__":
    main()
